"""Add Wishlist and Order + OrderItem models

Revision ID: 20155982393d
Revises: 
Create Date: 2026-04-25 07:15:48.944418

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '20155982393d'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    # Safely drop old unused tables if they exist
    op.execute('DROP TABLE IF EXISTS banner')
    op.execute('DROP TABLE IF EXISTS payment')
    op.execute('DROP TABLE IF EXISTS discount')
    op.execute('DROP TABLE IF EXISTS role')
    op.execute('DROP TABLE IF EXISTS product_supplier')
    op.execute('DROP TABLE IF EXISTS user_role')
    op.execute('DROP TABLE IF EXISTS setting')
    op.execute('DROP TABLE IF EXISTS shipment')
    op.execute('DROP TABLE IF EXISTS coupon')
    op.execute('DROP TABLE IF EXISTS log')
    op.execute('DROP TABLE IF EXISTS inventory')
    op.execute('DROP TABLE IF EXISTS audit_trail')
    op.execute('DROP TABLE IF EXISTS coupon_usage')
    op.execute('DROP TABLE IF EXISTS favorite')
    op.execute('DROP TABLE IF EXISTS address')
    op.execute('DROP TABLE IF EXISTS faq')
    op.execute('DROP TABLE IF EXISTS return')
    op.execute('DROP TABLE IF EXISTS feedback')
    op.execute('DROP TABLE IF EXISTS supplier')
    op.execute('DROP TABLE IF EXISTS coupon_usage')
    op.execute('DROP TABLE IF EXISTS audit_trail')
    op.execute('DROP TABLE IF EXISTS inventory')
    op.execute('DROP TABLE IF EXISTS log')
    op.execute('DROP TABLE IF EXISTS coupon')
    op.execute('DROP TABLE IF EXISTS shipment')
    op.execute('DROP TABLE IF EXISTS setting')
    op.execute('DROP TABLE IF EXISTS user_role')
    op.execute('DROP TABLE IF EXISTS product_supplier')
    op.execute('DROP TABLE IF EXISTS role')
    op.execute('DROP TABLE IF EXISTS discount')
    op.execute('DROP TABLE IF EXISTS payment')
    op.execute('DROP TABLE IF EXISTS favorite')
    op.execute('DROP TABLE IF EXISTS address')
    op.execute('DROP TABLE IF EXISTS faq')
    
    # Create indexes safely with IF NOT EXISTS (columns should already exist)
    op.execute('CREATE INDEX IF NOT EXISTS ix_cart_item_product_id ON cart_item (product_id)')
    op.execute('CREATE INDEX IF NOT EXISTS ix_cart_item_user_id ON cart_item (user_id)')
    op.execute('CREATE UNIQUE INDEX IF NOT EXISTS ix_category_name ON category (name)')
    op.execute('CREATE INDEX IF NOT EXISTS ix_message_created_at ON message (created_at)')
    op.execute('CREATE INDEX IF NOT EXISTS ix_message_receiver_id ON message (receiver_id)')
    op.execute('CREATE INDEX IF NOT EXISTS ix_message_sender_id ON message (sender_id)')
    op.execute('CREATE INDEX IF NOT EXISTS ix_notification_created_at ON notification (created_at)')
    op.execute('CREATE INDEX IF NOT EXISTS ix_notification_is_read ON notification (is_read)')
    op.execute('CREATE INDEX IF NOT EXISTS ix_notification_user_id ON notification (user_id)')
    op.execute('CREATE INDEX IF NOT EXISTS ix_order_status ON "order" (status)')
    op.execute('CREATE INDEX IF NOT EXISTS ix_order_user_id ON "order" (user_id)')
    op.execute('CREATE INDEX IF NOT EXISTS ix_order_item_order_id ON order_item (order_id)')
    op.execute('CREATE INDEX IF NOT EXISTS ix_order_item_product_id ON order_item (product_id)')
    op.execute('CREATE INDEX IF NOT EXISTS ix_product_category_id ON product (category_id)')
    op.execute('CREATE INDEX IF NOT EXISTS ix_product_is_active ON product (is_active)')
    op.execute('CREATE INDEX IF NOT EXISTS ix_product_merchant_id ON product (merchant_id)')
    op.execute('CREATE INDEX IF NOT EXISTS ix_product_name ON product (name)')
    op.execute('CREATE INDEX IF NOT EXISTS ix_product_price ON product (price)')
    op.execute('CREATE INDEX IF NOT EXISTS ix_review_product_id ON review (product_id)')
    op.execute('CREATE INDEX IF NOT EXISTS ix_review_user_id ON review (user_id)')
    op.execute('CREATE UNIQUE INDEX IF NOT EXISTS ix_user_email ON "user" (email)')
    op.execute('CREATE INDEX IF NOT EXISTS ix_user_is_admin ON "user" (is_admin)')
    op.execute('CREATE INDEX IF NOT EXISTS ix_user_is_merchant ON "user" (is_merchant)')
    op.execute('CREATE UNIQUE INDEX IF NOT EXISTS ix_user_username ON "user" (username)')
    op.execute('CREATE INDEX IF NOT EXISTS ix_wishlist_user_id ON wishlist (user_id)')
    op.execute('CREATE INDEX IF NOT EXISTS ix_wishlist_item_product_id ON wishlist_item (product_id)')
    op.execute('CREATE INDEX IF NOT EXISTS ix_wishlist_item_wishlist_id ON wishlist_item (wishlist_id)')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('wishlist_item', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_wishlist_item_wishlist_id'))
        batch_op.drop_index(batch_op.f('ix_wishlist_item_product_id'))
        batch_op.drop_column('added_at')

    with op.batch_alter_table('wishlist', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_wishlist_user_id'))
        batch_op.drop_column('created_at')

    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_user_username'))
        batch_op.drop_index(batch_op.f('ix_user_is_merchant'))
        batch_op.drop_index(batch_op.f('ix_user_is_admin'))
        batch_op.drop_index(batch_op.f('ix_user_email'))

    with op.batch_alter_table('review', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_review_user_id'))
        batch_op.drop_index(batch_op.f('ix_review_product_id'))

    with op.batch_alter_table('product', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_product_price'))
        batch_op.drop_index(batch_op.f('ix_product_name'))
        batch_op.drop_index(batch_op.f('ix_product_merchant_id'))
        batch_op.drop_index(batch_op.f('ix_product_is_active'))
        batch_op.drop_index(batch_op.f('ix_product_category_id'))
        batch_op.drop_column('created_at')

    with op.batch_alter_table('order_item', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_order_item_product_id'))
        batch_op.drop_index(batch_op.f('ix_order_item_order_id'))

    with op.batch_alter_table('order', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_order_user_id'))
        batch_op.drop_index(batch_op.f('ix_order_status'))
        batch_op.drop_column('updated_at')
        batch_op.drop_column('total_amount')

    with op.batch_alter_table('notification', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_notification_user_id'))
        batch_op.drop_index(batch_op.f('ix_notification_is_read'))
        batch_op.drop_index(batch_op.f('ix_notification_created_at'))

    with op.batch_alter_table('message', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_message_sender_id'))
        batch_op.drop_index(batch_op.f('ix_message_receiver_id'))
        batch_op.drop_index(batch_op.f('ix_message_created_at'))

    with op.batch_alter_table('category', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_category_name'))

    with op.batch_alter_table('cart_item', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_cart_item_user_id'))
        batch_op.drop_index(batch_op.f('ix_cart_item_product_id'))

    op.create_table('supplier',
    sa.Column('id', sa.INTEGER(), nullable=False),
    sa.Column('name', sa.VARCHAR(length=100), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('feedback',
    sa.Column('id', sa.INTEGER(), nullable=False),
    sa.Column('user_id', sa.INTEGER(), nullable=False),
    sa.Column('content', sa.TEXT(), nullable=False),
    sa.Column('created_at', sa.DATETIME(), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('return',
    sa.Column('id', sa.INTEGER(), nullable=False),
    sa.Column('order_item_id', sa.INTEGER(), nullable=False),
    sa.Column('reason', sa.VARCHAR(length=255), nullable=True),
    sa.ForeignKeyConstraint(['order_item_id'], ['order_item.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('faq',
    sa.Column('id', sa.INTEGER(), nullable=False),
    sa.Column('question', sa.VARCHAR(length=255), nullable=False),
    sa.Column('answer', sa.TEXT(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('address',
    sa.Column('id', sa.INTEGER(), nullable=False),
    sa.Column('user_id', sa.INTEGER(), nullable=False),
    sa.Column('address', sa.VARCHAR(length=255), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('favorite',
    sa.Column('id', sa.INTEGER(), nullable=False),
    sa.Column('user_id', sa.INTEGER(), nullable=False),
    sa.Column('product_id', sa.INTEGER(), nullable=False),
    sa.ForeignKeyConstraint(['product_id'], ['product.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('coupon_usage',
    sa.Column('id', sa.INTEGER(), nullable=False),
    sa.Column('coupon_id', sa.INTEGER(), nullable=False),
    sa.Column('user_id', sa.INTEGER(), nullable=False),
    sa.Column('used_at', sa.DATETIME(), nullable=True),
    sa.ForeignKeyConstraint(['coupon_id'], ['coupon.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('audit_trail',
    sa.Column('id', sa.INTEGER(), nullable=False),
    sa.Column('user_id', sa.INTEGER(), nullable=False),
    sa.Column('action', sa.VARCHAR(length=255), nullable=False),
    sa.Column('created_at', sa.DATETIME(), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('inventory',
    sa.Column('id', sa.INTEGER(), nullable=False),
    sa.Column('product_id', sa.INTEGER(), nullable=False),
    sa.Column('stock', sa.INTEGER(), nullable=False),
    sa.ForeignKeyConstraint(['product_id'], ['product.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('log',
    sa.Column('id', sa.INTEGER(), nullable=False),
    sa.Column('user_id', sa.INTEGER(), nullable=True),
    sa.Column('action', sa.VARCHAR(length=255), nullable=False),
    sa.Column('created_at', sa.DATETIME(), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('coupon',
    sa.Column('id', sa.INTEGER(), nullable=False),
    sa.Column('code', sa.VARCHAR(length=50), nullable=False),
    sa.Column('discount', sa.FLOAT(), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('code')
    )
    op.create_table('shipment',
    sa.Column('id', sa.INTEGER(), nullable=False),
    sa.Column('order_id', sa.INTEGER(), nullable=False),
    sa.Column('shipped_date', sa.DATETIME(), nullable=True),
    sa.ForeignKeyConstraint(['order_id'], ['order.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('setting',
    sa.Column('id', sa.INTEGER(), nullable=False),
    sa.Column('key', sa.VARCHAR(length=100), nullable=False),
    sa.Column('value', sa.VARCHAR(length=255), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('key')
    )
    op.create_table('user_role',
    sa.Column('id', sa.INTEGER(), nullable=False),
    sa.Column('user_id', sa.INTEGER(), nullable=False),
    sa.Column('role_id', sa.INTEGER(), nullable=False),
    sa.ForeignKeyConstraint(['role_id'], ['role.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('product_supplier',
    sa.Column('id', sa.INTEGER(), nullable=False),
    sa.Column('product_id', sa.INTEGER(), nullable=False),
    sa.Column('supplier_id', sa.INTEGER(), nullable=False),
    sa.ForeignKeyConstraint(['product_id'], ['product.id'], ),
    sa.ForeignKeyConstraint(['supplier_id'], ['supplier.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('role',
    sa.Column('id', sa.INTEGER(), nullable=False),
    sa.Column('name', sa.VARCHAR(length=50), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('name')
    )
    op.create_table('discount',
    sa.Column('id', sa.INTEGER(), nullable=False),
    sa.Column('product_id', sa.INTEGER(), nullable=False),
    sa.Column('discount_rate', sa.FLOAT(), nullable=False),
    sa.ForeignKeyConstraint(['product_id'], ['product.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('payment',
    sa.Column('id', sa.INTEGER(), nullable=False),
    sa.Column('order_id', sa.INTEGER(), nullable=False),
    sa.Column('paid_at', sa.DATETIME(), nullable=True),
    sa.Column('amount', sa.FLOAT(), nullable=False),
    sa.ForeignKeyConstraint(['order_id'], ['order.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('banner',
    sa.Column('id', sa.INTEGER(), nullable=False),
    sa.Column('image_url', sa.VARCHAR(length=255), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###
